# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://jiaxiang8756.github.io
date_format: "ordinal"
title: 栖迟於一丘
description: "栖迟於一丘，则天下不易其乐"
keywords: 笔记, C#, CIL, 写作, 代码
timezone: Asia/Hefei
encoding: "utf-8"
repository: jiaxiang8756/jiaxiang8756.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: true
        hide-platforms: qq,douban,qzone,linkedin,facebook,twitter
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2022-10-01
    # My Popular Repositories
    side_bar_repo:
        enabled: false
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: true
        image_alt: 南枫的寻宝之旅
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
#    wiki:
#        view: cate
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: 贾宏祥
organization: 
organization_url: 
github_username: jiaxiang8756
location: Hefei, China
email: jiaxiangjia@vip.qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

#   -
#     href: /open-source/
#     label: 开源

#  -
#    href: /wiki/
#    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: jiaxiang8756
    repo: blog-comments
    oauth:
        client_id: e0a61cbfac6d8ecc7c3e
        client_secret: 8da8b2baee0f87f7bfd590be3e90662d10b5fb54
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: jiaxiang8756
    repo: blog-comments
    clientID: 4f7879414dec361d8f2f
    clientSecret: af0e3a345cecb7f7acc29408cb4a3a0069bb144c
# https://utteranc.es/
utterances:
    repo: blog-comments
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
# google:
#     analytics_id: UA-80669434-1
#     adsense:
#         footer: true
#         sidebar: true 
#         sidebar-detail: true 
#         content_header: false
#         content_footer: false
